### ISSUE TITLE
ROADMAP of ComfyUI-Transformers

### ISSUE THREAD

**Issue by kadirnar** [kadirnar/ComfyUI-Transformers#12]
## Computer Vision:

- [x] Add Depth Estimation pipeline
- [x] Add Image Classification pipeline
- [x] Add Image Segmentation pipeline
- [x] Add Mask Generation pipeline
- [x] Add Object Detection pipeline
- [x] Add Zero-Shot Image Classification pipeline
- [x] Add Zero-Shot Object Detection pipeline

## Natural Language Processing:

- [ ] Add Conversational pipeline
- [ ] Add Fill-Mask pipeline
- [ ] Add Question Answering pipeline
- [ ] Add Sentence Similarity pipeline
- [ ] Add Summarization pipeline
- [ ] Add Table Question Answering pipeline
- [ ] Add Text Classification pipeline
- [ ] Add Text Generation pipeline
- [ ] Add Token Classification pipeline
- [ ] Add Translation pipeline
- [ ] Add Zero-Shot Classification pipeline

## Audio:

- [ ] Add Audio Classification pipeline
- [ ] Add Audio-to-Audio pipeline
- [ ] Add Automatic Speech Recognition pipeline
- [ ] Add Text-to-Speech pipeline
- [ ] Add Audio Classification pipeline

## Tabular:

- [ ] Add Tabular Classification pipeline
- [ ] Add Tabular Regression pipeline

## Multimodal:

- [ ] Add Document Question Answering pipeline
- [ ] Add Feature Extraction pipeline
- [ ] Add Image-to-Text pipeline
- [ ] Add Visual Question Answering pipeline

**Comment by EricRollei** [comment]
anyone still working on these nodes?
